### ISSUE TITLE
Table Formatting Issues

### ISSUE THREAD

**Issue by intmarine** [SMPTE/st429-18#1]
Re: ST 429-19 has been converted to HTML
While using Word for Mac version 16.70
Table 1 and 4 and 6 – Column 2 appears too close to Column 1 such that it doesn't appear under its column heading
Table 2 and 4 (and perhaps 6) – Headings appear to be Center Justified instead of Left Justified making them appear to be not part of the Table
Table 3 and 5 – Column widths are incorrect leaving Headings and column data illegible

QuibleQuestion: Table 1
Should tables indicate when data spills to next page?

**Comment by SteveLLamb** [comment]
CJ,

You have put this in the 429-18 GH issues, and mention 429-19. Can you clarify which document you are referring to, so I can move the issue to the appropriate repo?

**Comment by palemieux** [comment]
Close per email from @intmarine
